### ISSUE TITLE
examples fail in ubuntu 20.04 lts

### ISSUE THREAD

**Issue by teliot** [madmurphy/libconfini#14]
==> Please choose a number to compile and run (q to exit): 1
  -> Compiling "cplusplus/generic.cpp" with gcc
     (`g++ -Wall -pedantic -lconfini 'cplusplus/generic.cpp'`)...
/usr/bin/ld: /tmp/ccisF92m.o: in function `callback(IniDispatch*, void*)':
generic.cpp:(.text+0x43): undefined reference to `ini_array_match'
/usr/bin/ld: generic.cpp:(.text+0x65): undefined reference to `ini_string_match_ii'
/usr/bin/ld: generic.cpp:(.text+0xd9): undefined reference to `ini_array_match'
/usr/bin/ld: generic.cpp:(.text+0xfb): undefined reference to `ini_string_match_ii'
/usr/bin/ld: /tmp/ccisF92m.o: in function `main':
generic.cpp:(.text+0x19a): undefined reference to `load_ini_path'
collect2: error: ld returned 1 exit status
  -> Couldn't compile file "cplusplus/generic.cpp".

it compiles fine with this command
g++ -Wall -pedantic generic.cpp -lconfini

but then fails to run 
./a.out: error while loading shared libraries: libconfini.so.0: cannot open shared object file: No such file or directory

but works when i do this
./configure --prefix=/usr

i can reproduce the error with the following...
lxc launch ubuntu:20.04 delme
lxc shell delme
git clone https://github.com/madmurphy/libconfini.git
apt update
apt install -y libtool-bin autoconf automake make gawk g++
cd libconfini/
./bootstrap
make install
/usr/local/share/doc/libconfini/examples/run-example.sh

**Comment by madmurphy** [comment]
Hi Thomas,

Thank you for your message. I use Arch, but I believe that the fact that it works fine with `./configure --prefix=/usr` simply means that the `-lconfini` argument tells gcc to search for the library only in `/usr/lib` and not in `/usr/local/lib` (the latter is the default path chosen when you don't specify any `--prefix=` argument).

Normally when a package is created for a specific distribution the `--prefix=/usr` argument is always passed. I believe this problem is not specific to libconfini and maybe [this discussion][1] can be of help.

--madmurphy


  [1]: https://unix.stackexchange.com/questions/67781/use-shared-libraries-in-usr-local-lib

**Comment by teliot** [comment]
the placement of -lconfini at the end is independent of --prefix=/usr. I believe it is a change with the Gnu Compiler.

I am on GCC 10.2.0

**Comment by teliot** [comment]
That link is helpful, I will adjust my environment to resolve the --prefix issue I was having.

**Comment by madmurphy** [comment]
I am glad the link was useful!

--madmurphy
