### ISSUE TITLE
Question about licensing

### ISSUE THREAD

**Issue by telkamp** [madmurphy/libconfini#8]
I've compared some ini file parsers now, and libconfini really fits best to my needs: It is easy-to-use, compact and will also run on a very simple embedded system without considerable memory consumption or runtime overhead. Really a nice pice of software!

The only drawback is its license for me: Due to the roles of GPL v3.0, all the code using libconfini also has to be put under GPL v3.0. For open source projects this should be no problem, but for a commercial application like mine this is not possible.

Do you think it would be possible to put libconfini under a less restricted license like MIT, maybe under a dual-license?  Thank you!

**Comment by madmurphy** [comment]
@telkamp

Thank you for your words. I am particularly attached to this library and I am strong supporter of free software, so I think that having licensed it as GPLv3 was the right choice.

If you are dynamically linking it to a closed source software, however, [the situation is not so tragic][1]. I know the topic is rather unclear, but I will never sue you for a dynamic linking. And even if I did, I wouldn't be so sure I would win the trial. So don't worry.

The only important thing is that if you edit the source code of **libconfini**, you must release _that_ (and only that) as GPLv3.

--madmurphy


[1]: https://softwareengineering.stackexchange.com/questions/158789/can-i-link-to-a-gpl-library-from-a-closed-source-application

**Comment by telkamp** [comment]
Thank you for your quick response! 
Indeed, it seems that linking dynamically could be an option, but as you wrote already this is a bit spongy. 
Wouldn't it help to make the situation really clear if you put libconfini under LGPL v3.0, without weaken the idea of free software? In this case, linking dynamically is expressly allowed...
Thank you!

**Comment by madmurphy** [comment]
@telkamp

Licensing it as LGPL was an option I had considered, and I had done it with [other libraries][1]. However, one of the goals of GPL is exactly to force proprietary software to become free. Dynamic linking is a grey area, but exactly because it's a grey area it allows to try to take action against some cases on which LGPL explicitly gives up.

Yours is not one of these cases. But imagine that a big company creates a successful closed source software, such software heavily relies on an open source library, and this library is unique in its capabilities, ultimately better than any other closed software competitors. In this case most of the credit should go to the library, but nevertheless the money will go to the closed source software. Licensing this hypothetical library as GPL (instead of LGPL) will allow to try to force the closed source software to become GPL and open source.

In the case of this library it is an unlikely scenario. But there are a couple of things for which **libconfini** is unique at the moment – one of these, for instance, is the ability to distinguish disabled entries from comments. Now, imagine you work for Google and you create a GUI editor for editing INI files using my library, and you heavily exploit this feature for making yours the fanciest editor on the market… Well, in that case it might make sense to ask you to release your software as GPL.

It's just an ethical strategy. Maybe, to better understand this point, you could have a look at [this article][2].

But, as I said, you really shouldn't worry for your case. Just use it. I am just happy that you found my library useful.

--madmurphy


[1]: https://github.com/madmurphy/stringview.js
[2]: https://www.gnu.org/licenses/why-not-lgpl.html

**Comment by madmurphy** [comment]
@telkamp

Licensing it as LGPL was an option I had considered, and I had done it with [other libraries][1]. However, one of the goals of GPL is exactly to force proprietary software to become free. Dynamic linking is a grey area, but exactly because it's a grey area it allows to try to take action against some cases on which LGPL explicitly gives up.

Yours is not one of these cases. But imagine that a big company creates a successful closed source software, such software heavily relies on an open source library, and this library is unique in its capabilities, ultimately better than any other closed software competitors. In this case most of the credit should go to the library, but nevertheless the money will go to the closed source software. Licensing this hypothetical library as GPL (instead of LGPL) will allow to try to force the closed source software to become GPL and open source.

In the case of this library it is an unlikely scenario. But there are a couple of things for which **libconfini** is unique at the moment – one of these, for instance, is the ability to distinguish disabled entries from comments. Now, imagine you work for Google, you create a GUI editor for editing INI files using my library, and you heavily exploit this feature for making yours the fanciest editor on the market… Well, in that case it might make sense to ask you to release your software as GPL.

It's just an ethical strategy. Maybe, to better understand this point, you could have a look at [this article][2].

But, as I said, you really shouldn't worry for your case. Just use it. I am just happy that you found my library useful.

--madmurphy


[1]: https://github.com/madmurphy/stringview.js
[2]: https://www.gnu.org/licenses/why-not-lgpl.html

**Comment by telkamp** [comment]
Thank you for your explanation - and thank you for sharing libconfini!
I really like your library and would like to use it for open source projects.
Regarding commercial projects, there are customers who exclude to link their application against GPL-licensed third-party software. But of course, this is not always the case.

**Comment by mutech** [comment]
Hi @madmurphy  and @telkamp! Just read this conversation and it's like time traveling to a time when OSS and FS felt like synonyms.

It's sad, that apparently inclusion requires the exclusion of exclusion (ironically on both sides). Until relatively recently, it looked like cooperation between altruism and business in the from of OSS could work.

How do you guys feel about this topic five years later, now that things get more and more polarized?

**Comment by madmurphy** [comment]
Hi Michael.

Inclusion always requires exclusion of exclusion, independently if we live in a time in which that needs to be reminded or it just comes obvious and natural. An immortal god is excluded from the possibility of committing suicide independently if he lives in a time in which he has to be reminded of that or not.

What worries me is that year after year *the institutions* that were leading the process of software liberation (most notably the FSF) have been repeatedly attacked with very little resistance, sometimes even by “friendly fire”, and today we are feeling the effects of their loss of influence, at least by looking at how the FOSS community has been divided. That said, younger generations are not so affected by the past, and I still believe that in the long run “suicidable” licenses like MIT will be marginalized to minor projects, whereas copyleft licenses will be what to look for for major projects. And the reason is exactly what you can imagine: non-copyleft projects have the tendency to be cannibalized by large companies.

**Comment by mutech** [comment]
I guess the reason why the FSF did not succeed is not specific to FOSS. Most people don't like to fight, me included. The ultimate goal or ideal is to share and enjoy the mutual benefits of friendly acts. Taking a defensive stance against abuse may well be necessary, but it also diminishes or even removes what the whole thing was about. I think that's why RMS and GNU or the FSF have been increasingly marginalized, both by the industry and sadly also those who benefited from their work.

On the other hand, I find it hard to imagine how the landscape would look like today, had the FSF succeeded. In my understanding, free software lost to open source, not proprietary software. OSS belongs to corporations today. Had OSS not won (not quite sure if "winning" is the correct term for what happened), I guess it's more likely that we would see a more hardened front between proprietary and free software, where free software would probably be cut off from hardware.

I have the strong impression that most people do not care for their rights unless they are deprived of essential rights and then they would be too afraid and perplexed to do anything about it.

Sorry for annexing this issue, I just liked this conversation and it feels like similar exchanges are becoming increasingly rare in recent times.

**Comment by michaelsbradleyjr** [comment]
GCC famously has its [Runtime Library Exception](https://www.gnu.org/licenses/gcc-exception-3.1.en.html). In the [Rationale](https://www.gnu.org/licenses/gcc-exception-3.1-faq.html) doc it's stated

> …using small libraries to limit the use of GCC seemed like the tail wagging the dog.

The ship sailed on this library's license a long time ago, obviously. But…maybe there could be renewed consideration of adding a GPLv3 exception? `libconfini` is small, in a good way! and very well done – what a relief if you don't have to re/invent your own full-featured config parser, much less a format!

**Comment by madmurphy** [comment]
Hi Michael,

Thank you for appreciating libconfini! Believe me, it is not against anyone; it is _for_ users' sake that I like stick to GPL. Programmers have their own interests, and often programmers' interests are against users' interests.

Think for a moment that if only FreeBSD had stuck to a copyleft license, [Darwin](https://en.wikipedia.org/wiki/Darwin_%28operating_system%29) would have had a copyleft license too, and today macOS would have been free software.

libconfini is pretty small indeed. But I like to remind users that software that cares about them exists, even if sometimes it is only a small contribution.

And as a more general rule, I always release code under either the GPL or the AGPL license.

--madmurphy

**Comment by michaelsbradleyjr** [comment]
I understand. Thank you for your work on this library and the time you took to consider and reply to my comment. Open Source and Free Software are important in many ways, and I am thankful for authors, such as yourself, who champion those ideas.

> Think for a moment that if only FreeBSD had stuck to a copyleft license, [Darwin](https://en.wikipedia.org/wiki/Darwin_%28operating_system%29) would have had a copyleft license too, and today macOS would have been free software.

The [BSD licenses](https://en.wikipedia.org/wiki/BSD_licenses) appeared and evolved from 1988-1999, in connection with the original BSD software and the *nix that evolved from it e.g. FreeBSD. The [GPL](https://en.wikipedia.org/wiki/GNU_General_Public_License) also traces back to the same time period, 1985-89, with the [Emacs GPL](https://www.free-soft.org/gpl_history/emacs_gpl.html) in '85-88 followed by the GNU GPL version 1 in '89. So BSD (permissive) and GPL (copyleft) were more contemporaries than competitors, at least in their origins.

If permissively licensed BSD components had not been viable for [NeXTSTEP](https://en.wikipedia.org/wiki/NeXTSTEP), it *might* have been dead in the water or re/developed with very different internals and networking code. Apple *might* have gone with [BeOS](https://en.wikipedia.org/wiki/BeOS) instead of NEXTStep, or maybe still not, but in either case Apple's new OS (Mac OS X) and what followed very well might not have been the mostly POSIX-compliant OS that it was and still is today.

That's just a different take on the matter, I don't mean to be argumentative. I love GPL software, have used Emacs everyday for many years now.
